# Generated by Django 3.2.13 on 2022-07-27 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_notice_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_title', models.CharField(max_length=85, null=True)),
                ('events_content', models.TextField(max_length=85, null=True)),
                ('img', models.ImageField(null=True, upload_to='images/Notice')),
                ('video', models.FileField(null=True, upload_to='images/Notice/videos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.chairman')),
            ],
        ),
    ]
