# Generated by Django 3.2.13 on 2022-07-27 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='events_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.member')),
                ('notice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.notice')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.chairman')),
            ],
        ),
    ]
