# Generated by Django 3.2.13 on 2022-07-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_events_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='member_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('otp', models.IntegerField(default=459)),
                ('role', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('is_verfied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
