# Generated by Django 3.2.13 on 2022-07-27 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_member_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='member_login',
        ),
        migrations.AddField(
            model_name='member',
            name='member_id',
            field=models.ForeignKey(default='exit', on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
            preserve_default=False,
        ),
    ]
